<?php

namespace Database\Seeders;

use App\Models\Madin;
use Illuminate\Database\Seeder;

class MadinSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            /* grade.id = 1 */
            [
                'semester_id' => 1,
                'day' => 'Ahad',
                'grade_id' => 1,
                'madin_room_id' => 1,
                'lesson_id' => 1,
                'teacher_user_id' => 22,
            ],
            [
                'semester_id' => 1,
                'day' => 'Senin',
                'grade_id' => 1,
                'madin_room_id' => 1,
                'lesson_id' => 2,
                'teacher_user_id' => 23,
            ],
            [
                'semester_id' => 1,
                'day' => 'Selasa',
                'grade_id' => 1,
                'madin_room_id' => 1,
                'lesson_id' => 3,
                'teacher_user_id' => 24,
            ],
            [
                'semester_id' => 1,
                'day' => 'Rabu',
                'grade_id' => 1,
                'madin_room_id' => 1,
                'lesson_id' => 4,
                'teacher_user_id' => 25,
            ],
            [
                'semester_id' => 1,
                'day' => 'Jumat',
                'grade_id' => 1,
                'madin_room_id' => 1,
                'lesson_id' => 5,
                'teacher_user_id' => 26,
            ],
            [
                'semester_id' => 1,
                'day' => 'Sabtu',
                'grade_id' => 1,
                'madin_room_id' => 1,
                'lesson_id' => 6,
                'teacher_user_id' => 25,
            ],
            /* grade.id = 2 */
            [
                'semester_id' => 1,
                'day' => 'Ahad',
                'grade_id' => 2,
                'madin_room_id' => 2,
                'lesson_id' => 7,
                'teacher_user_id' => 27,
            ],
            [
                'semester_id' => 1,
                'day' => 'Senin',
                'grade_id' => 2,
                'madin_room_id' => 2,
                'lesson_id' => 8,
                'teacher_user_id' => 28,
            ],
            [
                'semester_id' => 1,
                'day' => 'Selasa',
                'grade_id' => 2,
                'madin_room_id' => 2,
                'lesson_id' => 4,
                'teacher_user_id' => 29,
            ],
            [
                'semester_id' => 1,
                'day' => 'Rabu',
                'grade_id' => 2,
                'madin_room_id' => 2,
                'lesson_id' => 3,
                'teacher_user_id' => 30,
            ],
            [
                'semester_id' => 1,
                'day' => 'Jumat',
                'grade_id' => 2,
                'madin_room_id' => 2,
                'lesson_id' => 5,
                'teacher_user_id' => 31,
            ],
            [
                'semester_id' => 1,
                'day' => 'Sabtu',
                'grade_id' => 2,
                'madin_room_id' => 2,
                'lesson_id' => 2,
                'teacher_user_id' => 32,
            ],
            /* grade.id = 3 */
            [
                'semester_id' => 1,
                'day' => 'Ahad',
                'grade_id' => 3,
                'madin_room_id' => 3,
                'lesson_id' => 2,
                'teacher_user_id' => 23,
            ],
            [
                'semester_id' => 1,
                'day' => 'Senin',
                'grade_id' => 3,
                'madin_room_id' => 3,
                'lesson_id' => 9,
                'teacher_user_id' => 33,
            ],
            [
                'semester_id' => 1,
                'day' => 'Selasa',
                'grade_id' => 3,
                'madin_room_id' => 3,
                'lesson_id' => 10,
                'teacher_user_id' => 33,
            ],
            [
                'semester_id' => 1,
                'day' => 'Rabu',
                'grade_id' => 3,
                'madin_room_id' => 3,
                'lesson_id' => 12,
                'teacher_user_id' => 26,
            ],
            [
                'semester_id' => 1,
                'day' => 'Jumat',
                'grade_id' => 3,
                'madin_room_id' => 3,
                'lesson_id' => 11,
                'teacher_user_id' => 34,
            ],
            [
                'semester_id' => 1,
                'day' => 'Sabtu',
                'grade_id' => 3,
                'madin_room_id' => 3,
                'lesson_id' => 12,
                'teacher_user_id' => 26,
            ],
            /* grade.id = 4 */
            [
                'semester_id' => 1,
                'day' => 'Ahad',
                'grade_id' => 4,
                'madin_room_id' => 4,
                'lesson_id' => 12,
                'teacher_user_id' => 35,
            ],
            [
                'semester_id' => 1,
                'day' => 'Senin',
                'grade_id' => 4,
                'madin_room_id' => 4,
                'lesson_id' => 11,
                'teacher_user_id' => 36,
            ],
            [
                'semester_id' => 1,
                'day' => 'Selasa',
                'grade_id' => 4,
                'madin_room_id' => 4,
                'lesson_id' => 2,
                'teacher_user_id' => 37,
            ],
            [
                'semester_id' => 1,
                'day' => 'Rabu',
                'grade_id' => 4,
                'madin_room_id' => 4,
                'lesson_id' => 10,
                'teacher_user_id' => 32,
            ],
            [
                'semester_id' => 1,
                'day' => 'Jumat',
                'grade_id' => 4,
                'madin_room_id' => 4,
                'lesson_id' => 12,
                'teacher_user_id' => 35,
            ],
            [
                'semester_id' => 1,
                'day' => 'Sabtu',
                'grade_id' => 4,
                'madin_room_id' => 4,
                'lesson_id' => 9,
                'teacher_user_id' => 38,
            ],
            /* grade.id = 5 */
            [
                'semester_id' => 1,
                'day' => 'Ahad',
                'grade_id' => 5,
                'madin_room_id' => 5,
                'lesson_id' => 13,
                'teacher_user_id' => 39,
            ],
            [
                'semester_id' => 1,
                'day' => 'Senin',
                'grade_id' => 5,
                'madin_room_id' => 5,
                'lesson_id' => 14,
                'teacher_user_id' => 40,
            ],
            [
                'semester_id' => 1,
                'day' => 'Selasa',
                'grade_id' => 5,
                'madin_room_id' => 5,
                'lesson_id' => 15,
                'teacher_user_id' => 41,
            ],
            [
                'semester_id' => 1,
                'day' => 'Rabu',
                'grade_id' => 5,
                'madin_room_id' => 5,
                'lesson_id' => 16,
                'teacher_user_id' => 42,
            ],
            [
                'semester_id' => 1,
                'day' => 'Jumat',
                'grade_id' => 5,
                'madin_room_id' => 5,
                'lesson_id' => 17,
                'teacher_user_id' => 39,
            ],
            [
                'semester_id' => 1,
                'day' => 'Sabtu',
                'grade_id' => 5,
                'madin_room_id' => 5,
                'lesson_id' => 18,
                'teacher_user_id' => 43,
            ],
            /* grade.id = 6 */
            [
                'semester_id' => 1,
                'day' => 'Ahad',
                'grade_id' => 6,
                'madin_room_id' => 6,
                'lesson_id' => 19,
                'teacher_user_id' => 44,
            ],
            [
                'semester_id' => 1,
                'day' => 'Senin',
                'grade_id' => 6,
                'madin_room_id' => 6,
                'lesson_id' => 29,
                'teacher_user_id' => 43,
            ],
            [
                'semester_id' => 1,
                'day' => 'Selasa',
                'grade_id' => 6,
                'madin_room_id' => 6,
                'lesson_id' => 21,
                'teacher_user_id' => 45,
            ],
            [
                'semester_id' => 1,
                'day' => 'Rabu',
                'grade_id' => 6,
                'madin_room_id' => 6,
                'lesson_id' => 22,
                'teacher_user_id' => 39,
            ],
            [
                'semester_id' => 1,
                'day' => 'Jumat',
                'grade_id' => 6,
                'madin_room_id' => 6,
                'lesson_id' => 23,
                'teacher_user_id' => 46,
            ],
            [
                'semester_id' => 1,
                'day' => 'Sabtu',
                'grade_id' => 6,
                'madin_room_id' => 6,
                'lesson_id' => 24,
                'teacher_user_id' => 47,
            ],
            /* grade.id = 7 */
            [
                'semester_id' => 1,
                'day' => 'Ahad',
                'grade_id' => 7,
                'madin_room_id' => 7,
                'lesson_id' => 25,
                'teacher_user_id' => 48,
            ],
            [
                'semester_id' => 1,
                'day' => 'Selasa',
                'grade_id' => 7,
                'madin_room_id' => 7,
                'lesson_id' => 26,
                'teacher_user_id' => 49,
            ],
            [
                'semester_id' => 1,
                'day' => 'Rabu',
                'grade_id' => 7,
                'madin_room_id' => 7,
                'lesson_id' => 27,
                'teacher_user_id' => 50,
            ],
            [
                'semester_id' => 1,
                'day' => 'Jumat',
                'grade_id' => 7,
                'madin_room_id' => 7,
                'lesson_id' => 28,
                'teacher_user_id' => 51,
            ],
            [
                'semester_id' => 1,
                'day' => 'Senin',
                'grade_id' => 1,
                'madin_room_id' => 1,
                'lesson_id' => 2,
                'teacher_user_id' => 23,
            ],
            [
                'semester_id' => 1,
                'day' => 'Selasa',
                'grade_id' => 1,
                'madin_room_id' => 1,
                'lesson_id' => 3,
                'teacher_user_id' => 24,
            ],
            [
                'semester_id' => 1,
                'day' => 'Rabu',
                'grade_id' => 1,
                'madin_room_id' => 1,
                'lesson_id' => 4,
                'teacher_user_id' => 25,
            ],
            [
                'semester_id' => 1,
                'day' => 'Jumat',
                'grade_id' => 1,
                'madin_room_id' => 1,
                'lesson_id' => 5,
                'teacher_user_id' => 26,
            ],
            [
                'semester_id' => 1,
                'day' => 'Sabtu',
                'grade_id' => 1,
                'madin_room_id' => 1,
                'lesson_id' => 6,
                'teacher_user_id' => 25,
            ],
            /* grade.id = 2 */
            [
                'semester_id' => 1,
                'day' => 'Ahad',
                'grade_id' => 2,
                'madin_room_id' => 2,
                'lesson_id' => 7,
                'teacher_user_id' => 27,
            ],
            [
                'semester_id' => 1,
                'day' => 'Senin',
                'grade_id' => 2,
                'madin_room_id' => 2,
                'lesson_id' => 8,
                'teacher_user_id' => 28,
            ],
            [
                'semester_id' => 1,
                'day' => 'Selasa',
                'grade_id' => 2,
                'madin_room_id' => 2,
                'lesson_id' => 4,
                'teacher_user_id' => 29,
            ],
            [
                'semester_id' => 1,
                'day' => 'Rabu',
                'grade_id' => 2,
                'madin_room_id' => 2,
                'lesson_id' => 3,
                'teacher_user_id' => 30,
            ],
            [
                'semester_id' => 1,
                'day' => 'Jumat',
                'grade_id' => 2,
                'madin_room_id' => 2,
                'lesson_id' => 5,
                'teacher_user_id' => 31,
            ],
            [
                'semester_id' => 1,
                'day' => 'Sabtu',
                'grade_id' => 2,
                'madin_room_id' => 2,
                'lesson_id' => 2,
                'teacher_user_id' => 32,
            ],
            /* grade.id = 3 */
            [
                'semester_id' => 1,
                'day' => 'Ahad',
                'grade_id' => 3,
                'madin_room_id' => 3,
                'lesson_id' => 2,
                'teacher_user_id' => 23,
            ],
            [
                'semester_id' => 1,
                'day' => 'Senin',
                'grade_id' => 3,
                'madin_room_id' => 3,
                'lesson_id' => 9,
                'teacher_user_id' => 33,
            ],
            [
                'semester_id' => 1,
                'day' => 'Selasa',
                'grade_id' => 3,
                'madin_room_id' => 3,
                'lesson_id' => 10,
                'teacher_user_id' => 33,
            ],
            [
                'semester_id' => 1,
                'day' => 'Rabu',
                'grade_id' => 3,
                'madin_room_id' => 3,
                'lesson_id' => 12,
                'teacher_user_id' => 26,
            ],
            [
                'semester_id' => 1,
                'day' => 'Jumat',
                'grade_id' => 3,
                'madin_room_id' => 3,
                'lesson_id' => 11,
                'teacher_user_id' => 34,
            ],
            [
                'semester_id' => 1,
                'day' => 'Sabtu',
                'grade_id' => 3,
                'madin_room_id' => 3,
                'lesson_id' => 12,
                'teacher_user_id' => 26,
            ],
            /* grade.id = 4 */
            [
                'semester_id' => 1,
                'day' => 'Ahad',
                'grade_id' => 4,
                'madin_room_id' => 4,
                'lesson_id' => 12,
                'teacher_user_id' => 35,
            ],
            [
                'semester_id' => 1,
                'day' => 'Senin',
                'grade_id' => 4,
                'madin_room_id' => 4,
                'lesson_id' => 11,
                'teacher_user_id' => 36,
            ],
            [
                'semester_id' => 1,
                'day' => 'Selasa',
                'grade_id' => 4,
                'madin_room_id' => 4,
                'lesson_id' => 2,
                'teacher_user_id' => 37,
            ],
            [
                'semester_id' => 1,
                'day' => 'Rabu',
                'grade_id' => 4,
                'madin_room_id' => 4,
                'lesson_id' => 10,
                'teacher_user_id' => 32,
            ],
            [
                'semester_id' => 1,
                'day' => 'Jumat',
                'grade_id' => 4,
                'madin_room_id' => 4,
                'lesson_id' => 12,
                'teacher_user_id' => 35,
            ],
            [
                'semester_id' => 1,
                'day' => 'Sabtu',
                'grade_id' => 4,
                'madin_room_id' => 4,
                'lesson_id' => 9,
                'teacher_user_id' => 38,
            ],
            /* grade.id = 5 */
            [
                'semester_id' => 1,
                'day' => 'Ahad',
                'grade_id' => 5,
                'madin_room_id' => 5,
                'lesson_id' => 13,
                'teacher_user_id' => 39,
            ],
            [
                'semester_id' => 1,
                'day' => 'Senin',
                'grade_id' => 5,
                'madin_room_id' => 5,
                'lesson_id' => 14,
                'teacher_user_id' => 40,
            ],
            [
                'semester_id' => 1,
                'day' => 'Selasa',
                'grade_id' => 5,
                'madin_room_id' => 5,
                'lesson_id' => 15,
                'teacher_user_id' => 41,
            ],
            [
                'semester_id' => 1,
                'day' => 'Rabu',
                'grade_id' => 5,
                'madin_room_id' => 5,
                'lesson_id' => 16,
                'teacher_user_id' => 42,
            ],
            [
                'semester_id' => 1,
                'day' => 'Jumat',
                'grade_id' => 5,
                'madin_room_id' => 5,
                'lesson_id' => 17,
                'teacher_user_id' => 39,
            ],
            [
                'semester_id' => 1,
                'day' => 'Sabtu',
                'grade_id' => 5,
                'madin_room_id' => 5,
                'lesson_id' => 18,
                'teacher_user_id' => 43,
            ],
            /* grade.id = 6 */
            [
                'semester_id' => 1,
                'day' => 'Ahad',
                'grade_id' => 6,
                'madin_room_id' => 6,
                'lesson_id' => 19,
                'teacher_user_id' => 44,
            ],
            [
                'semester_id' => 1,
                'day' => 'Senin',
                'grade_id' => 6,
                'madin_room_id' => 6,
                'lesson_id' => 20,
                'teacher_user_id' => 43,
            ],
            [
                'semester_id' => 1,
                'day' => 'Selasa',
                'grade_id' => 6,
                'madin_room_id' => 6,
                'lesson_id' => 21,
                'teacher_user_id' => 45,
            ],
            [
                'semester_id' => 1,
                'day' => 'Rabu',
                'grade_id' => 6,
                'madin_room_id' => 6,
                'lesson_id' => 22,
                'teacher_user_id' => 39,
            ],
            [
                'semester_id' => 1,
                'day' => 'Jumat',
                'grade_id' => 6,
                'madin_room_id' => 6,
                'lesson_id' => 23,
                'teacher_user_id' => 46,
            ],
            [
                'semester_id' => 1,
                'day' => 'Sabtu',
                'grade_id' => 6,
                'madin_room_id' => 6,
                'lesson_id' => 24,
                'teacher_user_id' => 47,
            ],
            /* grade.id = 7 */
            [
                'semester_id' => 1,
                'day' => 'Ahad',
                'grade_id' => 7,
                'madin_room_id' => 7,
                'lesson_id' => 25,
                'teacher_user_id' => 48,
            ],
            [
                'semester_id' => 1,
                'day' => 'Selasa',
                'grade_id' => 7,
                'madin_room_id' => 7,
                'lesson_id' => 26,
                'teacher_user_id' => 49,
            ],
            [
                'semester_id' => 1,
                'day' => 'Rabu',
                'grade_id' => 7,
                'madin_room_id' => 7,
                'lesson_id' => 27,
                'teacher_user_id' => 50,
            ],
            [
                'semester_id' => 1,
                'day' => 'Jumat',
                'grade_id' => 7,
                'madin_room_id' => 7,
                'lesson_id' => 28,
                'teacher_user_id' => 51,
            ],
        ];

        foreach ($data as $record) {
            Madin::create($record);
        }
    }
}
